### PR TITLE
Participatory process groups content blocks

### PR DESCRIPTION
**Pull request by entantoencuanto**
This PR:

* Upgrades the Decidim version to 0.23 and changes blueprints image file size validation to work with the release
* Adds an associations of blueprints with content blocks to allow having separated blueprints for different content blocks
* Makes changes to associate the blueprints with the content blocks on creation/update and change the current content block title instead of homepage. In this way the Content Block widget can be defined in other places than the organization homepage
* Registers the content block allowing it to be used in the participatory process groups landing pages (see decidim/decidim#6655)
* Changes tests and adds some examples to check that the module manages blueprints of each content block separately

### CODE REVIEW

**Comment by microstudi** [comment]
Thanks for this @entantoencuanto, this PR is meant to be merged when https://github.com/decidim/decidim/pull/6655 is released? or it should work right now?

**Comment by entantoencuanto** [comment]
Good point. I've tested in local environment and it works in develop branch without requiring the merge of decidim/decidim#6655, the only thing is that a navigation block is registered but is not available yet in groups.
Another detail is that once merged, if there were previously defined blueprints, they would not appear on the home page because they are not associated to the related content block. Maybe a task or a migration can be added to do it

**Comment by microstudi** [comment]
ok, thanks. I'll try to review and incorporate necessary migrations if needed. It might be that I'll wait until this feature is merged in master so it passes the reviews first.
Thanks again

**Comment by microstudi** [comment]
Hi @entantoencuanto I've just updated the module to work with version 0.23. Do you think you can resolve conflicts?
After that I'll review and prepare the next gem version.

**Comment by entantoencuanto** [comment]
Hi, @microstudi! It's ready, I've merged master, fixed a pair of errors and it's working again.

**Review by microstudi — CHANGES_REQUESTED** [review]
Hi, thanks for this, this is an excelent job!

I see that codecoverage is dropping, you think you can add a spec for this file?:
`app/cells/decidim/navigation_maps/content_blocks/groups_navigation_map_cell.rb`

**Comment by entantoencuanto** [comment]
Sure, I'll add some tests and let you know when it's ready

**Comment by entantoencuanto** [comment]
Hi, @microstudi! tests added. I've included a commit with a small fix removing a debug line in settings form cell

**Review by microstudi — APPROVED** [review]

**Pull request merged**
